### ISSUE TITLE
Update for compatibility to V10

### ISSUE THREAD

**Issue by ShadowK13** [Krigsmaskine/fvtt-macro-among-friends#1]
Is there any way this can be updated for V10? I tried to install by Manifest because that can sometimes work for V9 modules anyway. But I'm getting an error stating "The Macro Among Friends module does not provide a download URL that can be installed." I also tried to install manually by downloading the ZIP and extracting into the module folder, but got an error there too. Thanks!

![MacroAmongFriends](https://github.com/Krigsmaskine/fvtt-macro-among-friends/assets/68548089/7fd82aff-1efc-4e00-850b-dd8852a1df3d)

**Comment by ShadowK13** [comment]
Hey, sorry. It looks like Advanced Macros is able to do what this module did. So nevermind, I was just not looking in that direction

**Comment by Krigsmaskine** [comment]
All good, you discovered the same reason I stopped development. I don't 'redirect' to Advanced Macros 'cause it was in a flux of authors, but seems pretty stable now!
